// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Replace these values with your new Supabase project URL and anon key
const SUPABASE_URL = "https://mwlcegwuedypgljhxrfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13bGNlZ3d1ZWR5cGdsamh4cmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODgxMDYsImV4cCI6MjA2MTk2NDEwNn0.AkxemLL_8aE14A25q5HH6xUsi_lZRZQwvw_JgB5d4pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);